//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/05/17 - 09:36:54
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using BusinessObject.BusinessRules;

namespace BusinessObject
{
    [DataContract()]
    public partial class Invoice :BusinessObject
    {
        [DataMember()]
        public Int32 Id { get; set; }

        [DataMember()]
        public String CustomerName { get; set; }

        [DataMember()]
        public String EmployeName { get; set; }

        [DataMember()]
        public String Phone { get; set; }

        [DataMember()]
        public Nullable<Double> Total { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreateDate { get; set; }

        [DataMember()]
        public List<InvoiceProduct> InvoiceProducts { get; set; }

        public Invoice()
        {
            AddRule(new ValidateId("Id"));
        }

        public Invoice(Int32 id, String customerName, String employeName, String phone, Nullable<Double> total, Nullable<DateTime> createDate, List<InvoiceProduct> invoiceProducts)
        {
			this.Id = id;
			this.CustomerName = customerName;
			this.EmployeName = employeName;
			this.Phone = phone;
			this.Total = total;
			this.CreateDate = createDate;
			this.InvoiceProducts = invoiceProducts;
        }
    }
}
