//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/05/17 - 09:36:54
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using BusinessObject.BusinessRules;

namespace BusinessObject
{
    [DataContract()]
    public partial class InvoiceProduct :BusinessObject
    {
        [DataMember()]
        public Int32 Id { get; set; }

        [DataMember()]
        public Nullable<Int32> ProductId { get; set; }

        [DataMember()]
        public Nullable<Int32> InvoiceId { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreateDate { get; set; }

        [DataMember()]
        public Invoice Invoice { get; set; }

        [DataMember()]
        public Product Product { get; set; }

        public InvoiceProduct()
        {
            AddRule(new ValidateId("Id"));
        }

        public InvoiceProduct(Int32 id, Nullable<Int32> productId, Nullable<Int32> invoiceId, Nullable<DateTime> createDate, Invoice invoice, Product product)
        {
			this.Id = id;
			this.ProductId = productId;
			this.InvoiceId = invoiceId;
			this.CreateDate = createDate;
			this.Invoice = invoice;
			this.Product = product;
        }
    }
}
