//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/05/17 - 09:36:55
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using BusinessObject.BusinessRules;

namespace BusinessObject
{
    [DataContract()]
    public partial class Product : BusinessObject
    {
        [DataMember()]
        public Int32 Id { get; set; }

        [DataMember()]
        public String Name { get; set; }

        [DataMember()]
        public String ShortDesc { get; set; }

        [DataMember()]
        public String Image { get; set; }

        [DataMember()]
        public Nullable<Double> Price { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreateDate { get; set; }

        [DataMember()]
        public List<InvoiceProduct> InvoiceProducts { get; set; }

        public Product()
        {
            AddRule(new ValidateId("Id"));
        }

        public Product(Int32 id, String name, String shortDesc, String image, Nullable<Double> price,
                       Nullable<DateTime> createDate, List<InvoiceProduct> invoiceProducts)
            : this()
        {
            this.Id = id;
            this.Name = name;
            this.ShortDesc = shortDesc;
            this.Image = image;
            this.Price = price;
            this.CreateDate = createDate;
            this.InvoiceProducts = invoiceProducts;
        }
    }
}
