//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaminhCMS.Web.Admin.Usercontrol.Page {
    
    
    public partial class PageManager {
        
        /// <summary>
        /// PageTree1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LaminhCMS.Web.Admin.Usercontrol.Page.PageTree PageTree1;
        
        /// <summary>
        /// PageConfig1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LaminhCMS.Web.Admin.Usercontrol.Page.PageConfig PageConfig1;
    }
}
