//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObjects.EntityFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_UserControl
    {
        public CMS_UserControl()
        {
            this.CMS_Page_UserControl = new HashSet<CMS_Page_UserControl>();
        }
    
        public int UserControl_Id { get; set; }
        public string UserControl_Name { get; set; }
        public string UserControl_Source { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Create_By { get; set; }
        public Nullable<bool> Visible { get; set; }
        public Nullable<bool> Is_Delete { get; set; }
    
        public virtual ICollection<CMS_Page_UserControl> CMS_Page_UserControl { get; set; }
    }
}
