//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObjects.EntityFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_Page_UserControl
    {
        public int Page_UserControl_Id { get; set; }
        public Nullable<int> PageId { get; set; }
        public Nullable<int> UserControl_Id { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Create_By { get; set; }
        public Nullable<bool> Is_Delete { get; set; }
    
        public virtual CMS_UserControl CMS_UserControl { get; set; }
        public virtual CMS_Page CMS_Page { get; set; }
    }
}
